name: flobster
description: A high-performance Line of Business (LOB) Flutter Framework inspired by Claris FileMaker.
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'

workspace:
  - packages/flobster_core
  - packages/flobster_ui
  - packages/flobster_reporting
